name: Prod Environment

on:
    push:
        branches:
            - main

jobs:
    prod-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: say hello from prod
              run: echo "ðŸ‘‹ Hello from PROD environment"