name: stage Environment

on:
    push:
        branches:
            - stage

jobs:
    stage-jobs:
        runs-on: ubuntu-lastest

        steps:
            - name: say hello from stage
              run: echo "ðŸ‘‹ Hello from stage environment"